In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from matplotlib.colors import ListedColormap 
from sklearn.metrics import accuracy_score
import numpy as np

In [4]:
from sklearn.metrics import precision_score, recall_score, f1_score


In [5]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [6]:
# load data
dataframe = pd.read_csv('/content/drive/MyDrive/short_csv_latest_11-10-21.csv', sep = r',',skipinitialspace=True)

In [7]:
dataframe=dataframe.dropna(axis=1,how="any",thresh=None)

In [8]:
dataframe=dataframe.drop(columns=['Circuit Name'])

In [9]:
dataframe.astype(float)
pd.options.display.float_format = '{:.1f}'.format
dataframe

No. of primary input gates  No. of primary output gates  No. of wires  \
0                           257                          128        970168   
1                             2                            2           120   
2                             1                            1            67   
3                             4                            4           424   
4                            11                            8          1927   
..                          ...                          ...           ...   
473                          38                          321         35806   
474                          36                            7           408   
475                          50                           22          2947   
476                          50                           22          2947   
477                          50                           22          2947   

     No. of non-primary input gates  No. of non-primary output gates  \
0                            661048                           316608   
1                                85                               45   
2                                48                               26   
3                               284                              152   
4                              1333                              718   
..                              ...                              ...   
473                           27044                            15242   
474                             336                              160   
475                            2127                             1141   
476                            2127                             1141   
477                            2127                             1141   

     No. of 3 or more input gates          sum CC0          sum CC1  \
0                           55232       18790400.0       25838752.0   
1                               8           4337.0           2640.0   
2                               4           7799.0           4656.0   
3                              20          55204.0          37991.0   
4                              53 75148226289073.0 41453859876674.0   
..                            ...              ...              ...   
473                           297          20818.0          53103.0   
474                            19           2076.0           1046.0   
475                             5          20207.0          19978.0   
476                             5          20207.0          19978.0   
477                             5          20207.0          19978.0   

                sum CO  No. of AND  ...    Obth L =  60    Obth L =  65  \
0         1062307080.0       88416  ...          2744.0          2401.0   
1             172358.0           1  ...          2570.0          2248.8   
2             176428.0           1  ...          3725.6          3259.9   
3            5664984.0           2  ...         20834.4         18230.1   
4   3723866289844357.0          35  ... 3899295931520.0 3411883940080.0   
..                 ...         ...  ...             ...             ...   
473          2355603.0        3716  ...           168.4           147.4   
474            12332.0           4  ...            57.2            50.0   
475           429461.0           5  ...           272.4           238.3   
476           429461.0           5  ...           272.4           238.3   
477           429461.0           5  ...           272.4           238.3   

       Obth L =  70    Obth L =  75    Obth L =  80    Obth L =  85  \
0            2058.0          1715.0          1372.0          1029.0   
1            1927.5          1606.2          1285.0           963.8   
2            2794.2          2328.5          1862.8          1397.1   
3           15625.8         13021.5         10417.2          7812.9   
4   2924471948640.0 2437059957200.0 1949647965760.0 1462235974320.0   
..              ...    

In [10]:
t=dataframe.columns

In [11]:
names = t

In [12]:
#names

In [13]:
dataframe.replace([np.inf, -np.inf], np.nan, inplace=True)
dataframe.fillna('mean', inplace=True)

In [14]:
arr=np.array(dataframe.values)

In [15]:
#arr

In [16]:
X=arr[0:,1:604]
X=X.astype('float')
Y=(arr[0:,603]).astype('float')

In [17]:
#Y

In [18]:
#X

In [19]:
X.shape

(478, 603)

In [20]:
Y.shape

(478,)

WITHOUT LASSO ACCURACY

In [21]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size= 0.20, random_state=10)

In [22]:
Y_train = Y_train.astype(np.int32)
X_train = X_train.astype(np.int32)

In [23]:
Y_test = Y_test.astype(np.int32)
X_test = X_test.astype(np.int32)

In [24]:
Y_train.shape


(382,)

In [25]:
X_train.shape

(382, 603)

In [26]:
#Y_test.shape
X_test.shape

(96, 603)

In [27]:
Y_test.shape

(96,)

RANDOM FOREST

Ridge FEATURE EXTRACTION METHOD

In [28]:
#feature selection using moodel

from sklearn.linear_model import Lasso

In [29]:
X_train

array([[  321, 35800, 27043, ...,    17,     0,     1],
       [   32,  6701,  4821, ...,   306,     0,     1],
       [  123,  6062,  4386, ...,    14,     0,     0],
       ...,
       [   54, 19775, 13131, ...,  9670,     0,     0],
       [   22,  2957,  2134, ...,    41,     0,     1],
       [  123,  6093,  4409, ...,    16,     0,     1]], dtype=int32)

In [30]:
Y_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)

In [31]:
X_train.shape

(382, 603)

In [32]:
Y_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)

In [33]:
#encoded

In [34]:
#Y_train

In [35]:
X_train

array([[  321, 35800, 27043, ...,    17,     0,     1],
       [   32,  6701,  4821, ...,   306,     0,     1],
       [  123,  6062,  4386, ...,    14,     0,     0],
       ...,
       [   54, 19775, 13131, ...,  9670,     0,     0],
       [   22,  2957,  2134, ...,    41,     0,     1],
       [  123,  6093,  4409, ...,    16,     0,     1]], dtype=int32)

In [36]:
# import model
from sklearn.linear_model import ElasticNet

# Train the model
e_net = ElasticNet(alpha = 0.5)
e_net.fit(X_train, Y_train)

# calculate the prediction and mean square error
y_pred_elastic = e_net.predict(X_test)
mean_squared_error = np.mean((y_pred_elastic - Y_test)**2)
print("Mean Squared Error on test set", mean_squared_error)

e_net_coeff = pd.DataFrame()
e_net_coeff["Columns"] = names[:-1]
e_net_coeff['Coefficient Estimate'] = pd.Series(e_net.coef_)
e_net_coeff

Mean Squared Error on test set 0.04284108151147192


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.001e+00, tolerance: 5.058e-03
  model = cd_fast.enet_coordinate_descent(


Columns  Coefficient Estimate
0         No. of primary input gates                   0.0
1        No. of primary output gates                  -0.0
2                       No. of wires                   0.0
3     No. of non-primary input gates                  -0.0
4    No. of non-primary output gates                  -0.0
..                               ...                   ...
598                     Obth L =  80                   0.0
599                     Obth L =  85                   0.0
600                     Obth L =  90                   0.0
601                     Obth L =  95                   0.0
602                    Obth L =  100                   0.0

[603 rows x 2 columns]

In [37]:
e_net_coeff["Columns"]

0           No. of primary input gates
1          No. of primary output gates
2                         No. of wires
3       No. of non-primary input gates
4      No. of non-primary output gates
                    ...               
598                       Obth L =  80
599                       Obth L =  85
600                       Obth L =  90
601                       Obth L =  95
602                      Obth L =  100
Name: Columns, Length: 603, dtype: object

In [38]:
e_net_coeff['Coefficient Estimate']

0      0.0
1     -0.0
2      0.0
3     -0.0
4     -0.0
      ... 
598    0.0
599    0.0
600    0.0
601    0.0
602    0.0
Name: Coefficient Estimate, Length: 603, dtype: float64

In [39]:
from pandas import DataFrame

In [40]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 5.4 MB/s eta 0:00:00


In [41]:
import xlsxwriter
workbook=xlsxwriter.Workbook('rsh.xlsx')

In [42]:
from xlsxwriter import Workbook
df=pd.DataFrame((e_net_coeff['Coefficient Estimate']))
df=df.loc[~(df<=0).all(axis=1)]

In [43]:
df

Coefficient Estimate
2                     0.0
5                     0.0
6                     0.0
11                    0.0
27                    0.0
..                    ...
596                   0.0
597                   0.0
598                   0.0
599                   0.0
600                   0.0

[82 rows x 1 columns]

In [44]:
df.index

Int64Index([  2,   5,   6,  11,  27,  28,  29,  30,  36,  37,  40,  41,  44,
             48,  56,  57,  65,  68,  78,  79,  81,  82,  84,  86,  87,  98,
            100, 101, 103, 107, 110, 114, 116, 120, 121, 122, 126, 149, 151,
            206, 218, 233, 244, 357, 368, 369, 379, 382, 383, 388, 389, 412,
            422, 431, 433, 449, 538, 548, 551, 558, 559, 560, 561, 564, 582,
            583, 584, 585, 586, 587, 589, 590, 591, 592, 593, 594, 595, 596,
            597, 598, 599, 600],
           dtype='int64')

In [45]:
df.size

82

In [46]:
dd=[]
for l in df.index:
  for m in e_net_coeff['Coefficient Estimate'].index:
    if l==m:
      print(m)
      dd.append(m)
print(dd)
#for k in compare_column:

2
5
6
11
27
28
29
30
36
37
40
41
44
48
56
57
65
68
78
79
81
82
84
86
87
98
100
101
103
107
110
114
116
120
121
122
126
149
151
206
218
233
244
357
368
369
379
382
383
388
389
412
422
431
433
449
538
548
551
558
559
560
561
564
582
583
584
585
586
587
589
590
591
592
593
594
595
596
597
598
599
600
[2, 5, 6, 11, 27, 28, 29, 30, 36, 37, 40, 41, 44, 48, 56, 57, 65, 68, 78, 79, 81, 82, 84, 86, 87, 98, 100, 101, 103, 107, 110, 114, 116, 120, 121, 122, 126, 149, 151, 206, 218, 233, 244, 357, 368, 369, 379, 382, 383, 388, 389, 412, 422, 431, 433, 449, 538, 548, 551, 558, 559, 560, 561, 564, 582, 583, 584, 585, 586, 587, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600]


In [47]:
len(dd)

82

In [48]:
ee=e_net_coeff["Columns"][dd]

In [49]:
#ee

In [50]:
ee.index

Int64Index([  2,   5,   6,  11,  27,  28,  29,  30,  36,  37,  40,  41,  44,
             48,  56,  57,  65,  68,  78,  79,  81,  82,  84,  86,  87,  98,
            100, 101, 103, 107, 110, 114, 116, 120, 121, 122, 126, 149, 151,
            206, 218, 233, 244, 357, 368, 369, 379, 382, 383, 388, 389, 412,
            422, 431, 433, 449, 538, 548, 551, 558, 559, 560, 561, 564, 582,
            583, 584, 585, 586, 587, 589, 590, 591, 592, 593, 594, 595, 596,
            597, 598, 599, 600],
           dtype='int64')

In [51]:
writer=pd.ExcelWriter('shiva.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet5')
writer.save()
#df

In [52]:
  y = df.index

In [53]:
#df

In [54]:
y

Int64Index([  2,   5,   6,  11,  27,  28,  29,  30,  36,  37,  40,  41,  44,
             48,  56,  57,  65,  68,  78,  79,  81,  82,  84,  86,  87,  98,
            100, 101, 103, 107, 110, 114, 116, 120, 121, 122, 126, 149, 151,
            206, 218, 233, 244, 357, 368, 369, 379, 382, 383, 388, 389, 412,
            422, 431, 433, 449, 538, 548, 551, 558, 559, 560, 561, 564, 582,
            583, 584, 585, 586, 587, 589, 590, 591, 592, 593, 594, 595, 596,
            597, 598, 599, 600],
           dtype='int64')

In [55]:
dataframe.index

RangeIndex(start=0, stop=478, step=1)

In [56]:
dataframe.columns

Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)

In [57]:
compare_column= dataframe.columns

In [58]:
compare_column.astype

<bound method Index.astype of Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)>

In [59]:
#compare_column=compare_column.astype(int)

In [60]:
compare_column

Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)

In [61]:
cc=[]
for j in ee:
  for k in dataframe.columns:
    if j==k:
      print(j)
      cc.append(j)
print(cc)
#for k in compare_column:

No. of wires
No. of 3 or more input gates
sum CC0
No of NOT
p0 >= 0.1
P1 >= 0.9
P1 >= 0.8
P1 >= 0.7
p1 >= 0.1
SUM P0 * SUM C0
Average P1
Average CC0
MEDIAN HIGH P1
MEDIAN LOW P1
STANDARD DEVIATION P1
STANDARD DEVIATION CC0
POPULATION STANDARD DEVIATION CC0
POPULATION VARIANCE P1
ratio SUM(CC0)/SUM(CC1)
SUM CC1*SUM CC0
SUM CC1*SUM P0
SUM CC0*SUM CO
SUM CO*SUM P0
SUM P0*SUM P1
SUM CC0*SUM CC1*SUM P0*SUM P1*SUM CO
Min(CC0)
Min(CC1)
Max(CO)
SUM P1 * SUM P0 * SUM CO
SUM CC1 * SUM P1 * SUM PO
SUM CC0 * SUM CC1 * SUM P1
co > 100
Max CC(S)
Median Low CCS
Normalised CCS
Standard Deviation CCS
Variance CCS
ccs 95 - 100
No. of BUFF
fan_in_3 45 - 50
fan_in_4 1 - 5
Sum fan_in_5
fan_in_5 1 - 5
Geometric Mean in_nearest_pin
in_nearest_pin > 100
Sum out_nearest_pout
Population Variance out_nearest_pout
out_nearest_pout 1 - 5
out_nearest_pout 5 - 10
out_nearest_pout 30 - 35
out_nearest_pout 35 - 40
in_ff_1 1 - 5
in_ff_2 1 - 5
Geometric Mean in_ff_3
in_ff_3 5 - 10
in_ff_4 20 - 25
out_ff_5 20 - 25
Popula

In [62]:
pp=[]
for o in cc:
  for q in dataframe:
    if o==q:
      print(o)
      pp.append(o)
#print(pp)
#for k in compare_column:

No. of wires
No. of 3 or more input gates
sum CC0
No of NOT
p0 >= 0.1
P1 >= 0.9
P1 >= 0.8
P1 >= 0.7
p1 >= 0.1
SUM P0 * SUM C0
Average P1
Average CC0
MEDIAN HIGH P1
MEDIAN LOW P1
STANDARD DEVIATION P1
STANDARD DEVIATION CC0
POPULATION STANDARD DEVIATION CC0
POPULATION VARIANCE P1
ratio SUM(CC0)/SUM(CC1)
SUM CC1*SUM CC0
SUM CC1*SUM P0
SUM CC0*SUM CO
SUM CO*SUM P0
SUM P0*SUM P1
SUM CC0*SUM CC1*SUM P0*SUM P1*SUM CO
Min(CC0)
Min(CC1)
Max(CO)
SUM P1 * SUM P0 * SUM CO
SUM CC1 * SUM P1 * SUM PO
SUM CC0 * SUM CC1 * SUM P1
co > 100
Max CC(S)
Median Low CCS
Normalised CCS
Standard Deviation CCS
Variance CCS
ccs 95 - 100
No. of BUFF
fan_in_3 45 - 50
fan_in_4 1 - 5
Sum fan_in_5
fan_in_5 1 - 5
Geometric Mean in_nearest_pin
in_nearest_pin > 100
Sum out_nearest_pout
Population Variance out_nearest_pout
out_nearest_pout 1 - 5
out_nearest_pout 5 - 10
out_nearest_pout 30 - 35
out_nearest_pout 35 - 40
in_ff_1 1 - 5
in_ff_2 1 - 5
Geometric Mean in_ff_3
in_ff_3 5 - 10
in_ff_4 20 - 25
out_ff_5 20 - 25
Popula

In [63]:
len(pp)

82

In [64]:
len(dataframe)

478

In [65]:
bb=dataframe[pp[1]]

In [66]:
bb

0      55232
1          8
2          4
3         20
4         53
       ...  
473      297
474       19
475        5
476        5
477        5
Name: No. of 3 or more input gates, Length: 478, dtype: int64

In [67]:
dict_features = dict()
for i in range(len(pp)):
  dict_features[pp[i]] = np.asarray(dataframe[pp[i]])

In [68]:
#print(dict_features)

In [69]:
#dict_features.keys()

In [70]:
from xlsxwriter import Workbook
#a=DataForML
df1=pd.DataFrame((dict_features))
#df1=df.loc[~(df<=0).all(axis=1)]
writer=pd.ExcelWriter('final.xlsx',engine='xlsxwriter')
df1.to_excel(writer,sheet_name='Sheet5')
writer.save()
#df

In [71]:
#df1

In [72]:
df1.columns

Index(['No. of wires', 'No. of 3 or more input gates', 'sum CC0', 'No of NOT',
       'p0 >= 0.1', 'P1 >= 0.9', 'P1 >= 0.8', 'P1 >= 0.7', 'p1 >= 0.1',
       'SUM P0 * SUM C0', 'Average P1', 'Average CC0', 'MEDIAN HIGH P1',
       'MEDIAN LOW P1', 'STANDARD DEVIATION P1', 'STANDARD DEVIATION CC0',
       'POPULATION STANDARD DEVIATION CC0', 'POPULATION VARIANCE P1',
       'ratio SUM(CC0)/SUM(CC1)', 'SUM CC1*SUM CC0', 'SUM CC1*SUM P0',
       'SUM CC0*SUM CO', 'SUM CO*SUM P0', 'SUM P0*SUM P1',
       'SUM CC0*SUM CC1*SUM P0*SUM P1*SUM CO', 'Min(CC0)', 'Min(CC1)',
       'Max(CO)', 'SUM P1 * SUM P0 * SUM CO', 'SUM CC1 * SUM P1 * SUM PO',
       'SUM CC0 * SUM CC1 * SUM P1', 'co > 100', 'Max CC(S)', 'Median Low CCS',
       'Normalised CCS', 'Standard Deviation CCS', 'Variance CCS',
       'ccs 95 - 100', 'No. of BUFF', 'fan_in_3 45 - 50', 'fan_in_4 1 - 5',
       'Sum fan_in_5', 'fan_in_5 1 - 5', 'Geometric Mean in_nearest_pin',
       'in_nearest_pin > 100', 'Sum out_nearest_pout',
   

In [73]:
arr=df1.values

In [74]:
#arr

In [75]:
W=arr[0:,0:82]
W=W.astype('float')
#Z=(arr[1:,6]).astype('float')

In [76]:
#W

In [77]:
W.shape

(478, 82)

In [78]:
Y.shape

(478,)

In [79]:
Y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

AFTER FEATURE EXTRACTION WITH ELASTIC_NET

In [80]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
W_train, W_test, Y_train, Y_test= train_test_split(W, Y, test_size= 0.20, random_state=100)

In [81]:
Y_train = Y_train.astype(np.int32)
W_train = W_train.astype(np.int32)

In [82]:
Y_test = Y_test.astype(np.int32)
W_test = W_test.astype(np.int32)

In [83]:
print(Y_train.shape)
print(W_train.shape)


(382,)
(382, 82)


In [84]:
print(Y_test.shape)
print(W_test.shape)

(96,)
(96, 82)


In [85]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier
import pandas as pd


Random Forest

In [86]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [87]:

clf = RandomForestClassifier(n_estimators =10)

clf.fit(W_train, Y_train)


Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[10  2]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.98      1.00      0.99        84

    accuracy                           0.98        96
   macro avg       0.99      0.92      0.95        96
weighted avg       0.98      0.98      0.98        96

0.9791666666666666


SVM

In [88]:
from sklearn.svm import LinearSVC


In [89]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC( random_state=0)  
classifier.fit(W_train, Y_train) 

SVC(random_state=0)

In [90]:
Y_pred= classifier.predict(W_test) 

In [91]:
print(confusion_matrix(Y_test,Y_pred))
#print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test, Y_pred)*100)
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))


[[ 9  3]
 [ 0 84]]
96.875
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.97      1.00      0.98        84

    accuracy                           0.97        96
   macro avg       0.98      0.88      0.92        96
weighted avg       0.97      0.97      0.97        96



Logestic regression

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:

clf = LogisticRegression(random_state=0, solver='liblinear', max_iter=500,multi_class='ovr')
clf.fit(W_train, Y_train)

    
Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
#print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))


[[ 8  4]
 [ 0 84]]
95.83333333333334
              precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.95      1.00      0.98        84

    accuracy                           0.96        96
   macro avg       0.98      0.83      0.89        96
weighted avg       0.96      0.96      0.95        96



In [94]:
print('Recall: %.3f' % recall_score(Y_test, Y_pred))

Recall: 1.000


In [95]:
#k-neighbors

KNN

In [96]:
from sklearn.neighbors import KNeighborsClassifier


In [97]:

          
clf = KNeighborsClassifier(n_neighbors=3)
    
clf.fit(W_train, Y_train)

Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)

[[ 8  4]
 [ 1 83]]
              precision    recall  f1-score   support

           0       0.89      0.67      0.76        12
           1       0.95      0.99      0.97        84

    accuracy                           0.95        96
   macro avg       0.92      0.83      0.87        96
weighted avg       0.95      0.95      0.94        96

94.79166666666666


In [98]:
print('Recall: %.3f' % recall_score(Y_test, Y_pred))

Recall: 0.988


XGBOOST CLASSIFIER

In [99]:
from xgboost import XGBClassifier


In [100]:

   
clf = XGBClassifier(n_estimators=20)
    
clf.fit(W_train, Y_train)
   
    
Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
  
accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)

[[ 9  3]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.97      1.00      0.98        84

    accuracy                           0.97        96
   macro avg       0.98      0.88      0.92        96
weighted avg       0.97      0.97      0.97        96

96.875


DECISION TREE CLASSIFIER

In [101]:
from sklearn.tree import DecisionTreeClassifier 

clf = DecisionTreeClassifier()

clf = clf.fit(W_train,Y_train)

Y_pred = clf.predict(W_test)


In [102]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
Accuracy= 100 * accuracy_score(Y_test, Y_pred)
print(Accuracy)


[[12  0]
 [ 3 81]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        12
           1       1.00      0.96      0.98        84

    accuracy                           0.97        96
   macro avg       0.90      0.98      0.94        96
weighted avg       0.97      0.97      0.97        96

96.875


GAUSSIAN NAIVE BAYE'S

In [103]:
from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()


# fit the model
gnb.fit(W_train, Y_train)

Y_pred = gnb.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
accuracy = 100 * (accuracy_score(Y_test, Y_pred))
print(accuracy)

[[ 7  5]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.58      0.74        12
           1       0.94      1.00      0.97        84

    accuracy                           0.95        96
   macro avg       0.97      0.79      0.85        96
weighted avg       0.95      0.95      0.94        96

94.79166666666666


Ensemble Learning

In [104]:
from sklearn.ensemble import VotingClassifier

#model_1 = LogisticRegression(random_state=0, solver='liblinear', max_iter=300, multi_class='ovr')
model_2 = XGBClassifier(n_estimators=20)
model_3 = RandomForestClassifier(n_estimators=5, max_depth=5, random_state=1)
model_4 = KNeighborsClassifier(n_neighbors=3)
#model_5 = SVC(kernel="rbf", C=10, gamma=1)
final_model = VotingClassifier(estimators=[#('lr', model_1), 
                                             ('xgb', model_2), 
                                             ('rf', model_3), 
                                             ('knn',model_4)])
                                           #  ('svm', model_5)], voting='hard')
final_model.fit(W_train, Y_train)


Y_pred = final_model.predict(W_test)

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)
  
print("Accuracy = %.2f" % (accuracy))



[[ 9  3]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.97      1.00      0.98        84

    accuracy                           0.97        96
   macro avg       0.98      0.88      0.92        96
weighted avg       0.97      0.97      0.97        96

Accuracy = 96.88
