In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from matplotlib.colors import ListedColormap 
from sklearn.metrics import accuracy_score
import numpy as np

In [4]:
from sklearn.metrics import precision_score, recall_score, f1_score


In [5]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [6]:
# load data
dataframe = pd.read_csv('/content/drive/MyDrive/short_csv_latest_11-10-21.csv', sep = r',',skipinitialspace=True)

In [7]:
dataframe=dataframe.dropna(axis=1,how="any",thresh=None)

In [8]:
dataframe=dataframe.drop(columns=['Circuit Name'])

In [9]:
dataframe.astype(float)
pd.options.display.float_format = '{:.1f}'.format
#dataframe

In [10]:
t=dataframe.columns

In [11]:
names = t

In [12]:
#names

In [13]:
dataframe.replace([np.inf, -np.inf], np.nan, inplace=True)
dataframe.fillna('mean', inplace=True)

In [14]:
arr=np.array(dataframe.values)

In [15]:
#arr

In [16]:
X=arr[0:,1:604]
X=X.astype('float')
Y=(arr[0:,603]).astype('float')

In [17]:
#Y

In [18]:
#X

In [19]:
X.shape

(478, 603)

In [20]:
Y.shape

(478,)

In [21]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size= 0.20, random_state=10)

In [22]:
Y_train = Y_train.astype(np.int32)
X_train = X_train.astype(np.int32)

In [23]:
Y_test = Y_test.astype(np.int32)
X_test = X_test.astype(np.int32)

Ridge FEATURE EXTRACTION METHOD

RANDOM FOREST

In [24]:
X_train

array([[  321, 35800, 27043, ...,    17,     0,     1],
       [   32,  6701,  4821, ...,   306,     0,     1],
       [  123,  6062,  4386, ...,    14,     0,     0],
       ...,
       [   54, 19775, 13131, ...,  9670,     0,     0],
       [   22,  2957,  2134, ...,    41,     0,     1],
       [  123,  6093,  4409, ...,    16,     0,     1]], dtype=int32)

In [25]:
Y_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)

In [26]:
X_train.shape

(382, 603)

In [27]:
Y_test

array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)

In [28]:
#encoded

In [29]:
#Y_train

In [30]:
X_train

array([[  321, 35800, 27043, ...,    17,     0,     1],
       [   32,  6701,  4821, ...,   306,     0,     1],
       [  123,  6062,  4386, ...,    14,     0,     0],
       ...,
       [   54, 19775, 13131, ...,  9670,     0,     0],
       [   22,  2957,  2134, ...,    41,     0,     1],
       [  123,  6093,  4409, ...,    16,     0,     1]], dtype=int32)

In [31]:
from sklearn.linear_model import Ridge

ridgeR = Ridge(alpha = 1)
ridgeR.fit(X_train, Y_train)
y_pred = ridgeR.predict(X_test)

mean_squared_error_ridge = np.mean((y_pred - Y_test)**2)
print(mean_squared_error_ridge)

ridge_coefficient = pd.DataFrame()
ridge_coefficient["Columns"]= names[:-1]

ridge_coefficient['Coefficient Estimate'] = pd.Series(ridgeR.coef_)
print(ridge_coefficient)


5870538022.346157
                             Columns  Coefficient Estimate
0         No. of primary input gates                   0.0
1        No. of primary output gates                  -0.0
2                       No. of wires                   0.0
3     No. of non-primary input gates                  -0.0
4    No. of non-primary output gates                   0.0
..                               ...                   ...
598                     Obth L =  80                   0.0
599                     Obth L =  85                   0.0
600                     Obth L =  90                   0.0
601                     Obth L =  95                   0.0
602                    Obth L =  100                   0.0

[603 rows x 2 columns]


/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_ridge.py:255: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.
  warnings.warn(


In [32]:
#ridge_coefficient["Columns"]

In [33]:
ridge_coefficient["Columns"].index

RangeIndex(start=0, stop=603, step=1)

In [34]:
ridge_coefficient.columns

Index(['Columns', 'Coefficient Estimate'], dtype='object')

In [35]:
ridge_coefficient.index

RangeIndex(start=0, stop=603, step=1)

In [36]:
#ridge_coefficient['Coefficient Estimate']

In [37]:
ridge_coefficient['Coefficient Estimate'].index

RangeIndex(start=0, stop=603, step=1)

In [38]:
#ridge_coefficient['Coefficient Estimate'].sort_values(ascending=False)


In [39]:
from pandas import DataFrame


In [40]:
(ridge_coefficient['Coefficient Estimate']).dtype

dtype('float64')

In [41]:
!pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 5.1 MB/s eta 0:00:00


In [42]:
import xlsxwriter
workbook=xlsxwriter.Workbook('rsh.xlsx')

In [43]:
from xlsxwriter import Workbook
df=pd.DataFrame((ridge_coefficient['Coefficient Estimate']))
df=df.loc[~(df<=0).all(axis=1)]

In [44]:
#df

In [45]:
df.index

Int64Index([  0,   2,   4,   6,   7,  10,  11,  12,  15,  27,
            ...
            584, 585, 586, 587, 596, 597, 598, 599, 600, 602],
           dtype='int64', length=256)

In [46]:
df.size

256

In [47]:
dd=[]
for l in df.index:
  for m in ridge_coefficient['Coefficient Estimate'].index:
    if l==m:
      print(m)
      dd.append(m)
print(dd)
#for k in compare_column:

0
2
4
6
7
10
11
12
15
27
28
37
40
41
44
45
48
49
56
57
61
64
65
68
74
77
78
81
82
84
86
89
91
92
94
96
98
99
100
101
105
106
107
110
111
117
120
121
122
123
125
127
128
131
132
134
135
136
137
138
141
145
146
147
148
149
151
152
155
156
158
159
160
161
162
163
167
168
169
170
171
172
175
176
177
180
182
186
188
189
191
192
193
194
195
197
198
200
203
204
205
208
209
210
211
212
213
216
219
220
223
234
235
236
237
242
246
247
248
249
253
256
274
275
283
288
289
290
291
292
295
302
303
314
315
323
328
329
330
331
332
335
342
343
345
354
355
357
359
360
361
362
363
364
365
366
367
368
369
378
381
383
384
397
398
399
400
401
422
423
424
425
426
427
428
429
432
441
442
443
445
447
448
449
451
454
455
456
457
458
461
463
464
465
473
474
475
483
485
486
487
495
498
499
500
503
504
506
507
514
518
519
520
521
522
523
533
539
540
541
542
543
544
546
549
550
555
556
557
558
559
560
561
562
563
564
566
569
570
576
577
578
579
581
582
583
584
585
586
587
596
597
598
599
600
602
[0, 2, 4, 6, 7, 10,

In [48]:
len(dd)

256

In [49]:
ee=ridge_coefficient["Columns"][dd]

In [50]:
#ee

In [51]:
ee.index

Int64Index([  0,   2,   4,   6,   7,  10,  11,  12,  15,  27,
            ...
            584, 585, 586, 587, 596, 597, 598, 599, 600, 602],
           dtype='int64', length=256)

In [52]:
writer=pd.ExcelWriter('shiva.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet5')
writer.save()
#df

In [53]:
  y = df.index

In [54]:
#df

In [55]:
y

Int64Index([  0,   2,   4,   6,   7,  10,  11,  12,  15,  27,
            ...
            584, 585, 586, 587, 596, 597, 598, 599, 600, 602],
           dtype='int64', length=256)

In [56]:
dataframe.index

RangeIndex(start=0, stop=478, step=1)

In [57]:
dataframe.columns

Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)

In [58]:
compare_column= dataframe.columns

In [59]:
compare_column.astype

<bound method Index.astype of Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)>

In [60]:
#compare_column=compare_column.astype(int)

In [61]:
compare_column

Index(['No. of primary input gates', 'No. of primary output gates',
       'No. of wires', 'No. of non-primary input gates',
       'No. of non-primary output gates', 'No. of 3 or more input gates',
       'sum CC0', 'sum CC1', 'sum CO', 'No. of AND',
       ...
       'Obth L =  60', 'Obth L =  65', 'Obth L =  70', 'Obth L =  75',
       'Obth L =  80', 'Obth L =  85', 'Obth L =  90', 'Obth L =  95',
       'Obth L =  100', 'Label'],
      dtype='object', length=604)

In [62]:
cc=[]
for j in ee:
  for k in dataframe.columns:
    if j==k:
      print(j)
      cc.append(j)
print(cc)
#for k in compare_column:

No. of primary input gates
No. of wires
No. of non-primary output gates
sum CC0
sum CC1
No. of OR
No of NOT
No of NAND
No. of XOR
p0 >= 0.1
P1 >= 0.9
SUM P0 * SUM C0
Average P1
Average CC0
MEDIAN HIGH P1
MEDIAN HIGH CC0
MEDIAN LOW P1
MEDIAN LOW CC0
STANDARD DEVIATION P1
STANDARD DEVIATION CC0
HARMONIC MEAN CC0
POPULATION STANDARD DEVIATION P1
POPULATION STANDARD DEVIATION CC0
POPULATION VARIANCE P1
GEOMETRIC MEAN P1
ratio SUM(P0)/SUM(P1)
ratio SUM(CC0)/SUM(CC1)
SUM CC1*SUM P0
SUM CC0*SUM CO
SUM CO*SUM P0
SUM P0*SUM P1
SUM CC0*SUM CC1*SUM P0*SUM CO
SUM CC0*SUM P0*SUM P1*SUM CO
SUM CC1*SUM P0*SUM P1*SUM CO
Min(P0)
Min(P1)
Min(CC0)
Max(CC1)
Min(CC1)
Max(CO)
SUM CC0 * SUM P1 * SUM CO
SUM CC0 * SUM P0 * SUM CO
SUM CC1 * SUM P1 * SUM PO
SUM CC0 * SUM CC1 * SUM P1
SUM CC0 * SUM CC1 * SUM P0
Min CC(S)
Median Low CCS
Normalised CCS
Standard Deviation CCS
Harmonic Mean CCS
Population Variance
Geometric Mean CCS
cc0 > 100
ccs 5 - 10
ccs 10 - 15
ccs 20 - 25
ccs 25 - 30
ccs 30 - 35
ccs 35 - 40
ccs 

In [63]:
pp=[]
for o in cc:
  for q in dataframe:
    if o==q:
      print(o)
      pp.append(o)
#print(pp)
#for k in compare_column:

No. of primary input gates
No. of wires
No. of non-primary output gates
sum CC0
sum CC1
No. of OR
No of NOT
No of NAND
No. of XOR
p0 >= 0.1
P1 >= 0.9
SUM P0 * SUM C0
Average P1
Average CC0
MEDIAN HIGH P1
MEDIAN HIGH CC0
MEDIAN LOW P1
MEDIAN LOW CC0
STANDARD DEVIATION P1
STANDARD DEVIATION CC0
HARMONIC MEAN CC0
POPULATION STANDARD DEVIATION P1
POPULATION STANDARD DEVIATION CC0
POPULATION VARIANCE P1
GEOMETRIC MEAN P1
ratio SUM(P0)/SUM(P1)
ratio SUM(CC0)/SUM(CC1)
SUM CC1*SUM P0
SUM CC0*SUM CO
SUM CO*SUM P0
SUM P0*SUM P1
SUM CC0*SUM CC1*SUM P0*SUM CO
SUM CC0*SUM P0*SUM P1*SUM CO
SUM CC1*SUM P0*SUM P1*SUM CO
Min(P0)
Min(P1)
Min(CC0)
Max(CC1)
Min(CC1)
Max(CO)
SUM CC0 * SUM P1 * SUM CO
SUM CC0 * SUM P0 * SUM CO
SUM CC1 * SUM P1 * SUM PO
SUM CC0 * SUM CC1 * SUM P1
SUM CC0 * SUM CC1 * SUM P0
Min CC(S)
Median Low CCS
Normalised CCS
Standard Deviation CCS
Harmonic Mean CCS
Population Variance
Geometric Mean CCS
cc0 > 100
ccs 5 - 10
ccs 10 - 15
ccs 20 - 25
ccs 25 - 30
ccs 30 - 35
ccs 35 - 40
ccs 

In [64]:
len(pp)

256

In [65]:
len(dataframe)

478

In [66]:
bb=dataframe[pp[1]]

In [67]:
bb

0      970168
1         120
2          67
3         424
4        1927
        ...  
473     35806
474       408
475      2947
476      2947
477      2947
Name: No. of wires, Length: 478, dtype: int64

In [68]:
dict_features = dict()
for i in range(len(pp)):
  dict_features[pp[i]] = np.asarray(dataframe[pp[i]])

In [69]:
#print(dict_features)

In [70]:
#dict_features.keys()

In [71]:
from xlsxwriter import Workbook
#a=DataForML
df1=pd.DataFrame((dict_features))
#df1=df.loc[~(df<=0).all(axis=1)]
writer=pd.ExcelWriter('final.xlsx',engine='xlsxwriter')
df1.to_excel(writer,sheet_name='Sheet5')
writer.save()
#df

In [72]:
#df1

In [73]:
df1.columns

Index(['No. of primary input gates', 'No. of wires',
       'No. of non-primary output gates', 'sum CC0', 'sum CC1', 'No. of OR',
       'No of NOT', 'No of NAND', 'No. of XOR', 'p0 >= 0.1',
       ...
       'Obth L =  10', 'Obth L =  15', 'Obth L =  20', 'Obth L =  25',
       'Obth L =  70', 'Obth L =  75', 'Obth L =  80', 'Obth L =  85',
       'Obth L =  90', 'Obth L =  100'],
      dtype='object', length=256)

In [74]:
arr=df1.values

In [75]:
#arr

In [76]:
W=arr[0:,0:342]
W=W.astype('float')
#Z=(arr[1:,6]).astype('float')

In [77]:
#W

In [78]:
W.shape

(478, 256)

In [79]:
Y.shape

(478,)

In [80]:
Y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

AFTER FEATURE EXTRACTION WITH Ridge

In [81]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
W_train, W_test, Y_train, Y_test= train_test_split(W, Y, test_size= 0.20, random_state=100)

In [82]:
Y_train = Y_train.astype(np.int32)
W_train = W_train.astype(np.int32)

In [83]:
Y_test = Y_test.astype(np.int32)
W_test = W_test.astype(np.int32)

In [84]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier
import pandas as pd


Random Forest

In [85]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [86]:

clf = RandomForestClassifier(n_estimators =10)

clf.fit(W_train, Y_train)


Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[11  1]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.99      1.00      0.99        84

    accuracy                           0.99        96
   macro avg       0.99      0.96      0.98        96
weighted avg       0.99      0.99      0.99        96

0.9895833333333334


SVM

In [87]:
from sklearn.svm import LinearSVC


In [88]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC( random_state=0)  
classifier.fit(W_train, Y_train) 

SVC(random_state=0)

In [89]:
Y_pred= classifier.predict(W_test) 

In [90]:
print(confusion_matrix(Y_test,Y_pred))
#print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test, Y_pred)*100)
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))


[[ 8  4]
 [ 0 84]]
95.83333333333334
              precision    recall  f1-score   support

           0       1.00      0.67      0.80        12
           1       0.95      1.00      0.98        84

    accuracy                           0.96        96
   macro avg       0.98      0.83      0.89        96
weighted avg       0.96      0.96      0.95        96



Logestic regression

In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:

clf = LogisticRegression(random_state=0, solver='liblinear', max_iter=500,multi_class='ovr')
clf.fit(W_train, Y_train)

    
Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
#print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)
from sklearn import metrics
print(metrics.classification_report(Y_test, Y_pred))


[[ 9  3]
 [ 0 84]]
96.875
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.97      1.00      0.98        84

    accuracy                           0.97        96
   macro avg       0.98      0.88      0.92        96
weighted avg       0.97      0.97      0.97        96



In [93]:
print('Recall: %.3f' % recall_score(Y_test, Y_pred))

Recall: 1.000


KNN

In [94]:
from sklearn.neighbors import KNeighborsClassifier


In [95]:

          
clf = KNeighborsClassifier(n_neighbors=3)
    
clf.fit(W_train, Y_train)

Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)

[[ 9  3]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.97      1.00      0.98        84

    accuracy                           0.97        96
   macro avg       0.98      0.88      0.92        96
weighted avg       0.97      0.97      0.97        96

96.875


In [96]:
print('Recall: %.3f' % recall_score(Y_test, Y_pred))

Recall: 1.000


XGBOOST CLASSIFIER

In [97]:
from xgboost import XGBClassifier


In [98]:

   
clf = XGBClassifier(n_estimators=20)
    
clf.fit(W_train, Y_train)
   
    
Y_pred = clf.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
  
accuracy = 100 * accuracy_score(Y_test, Y_pred)

print(accuracy)

[[12  0]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        84

    accuracy                           1.00        96
   macro avg       1.00      1.00      1.00        96
weighted avg       1.00      1.00      1.00        96

100.0


DECISION TREE CLASSIFIER

In [99]:
from sklearn.tree import DecisionTreeClassifier 

clf = DecisionTreeClassifier()

clf = clf.fit(W_train,Y_train)

Y_pred = clf.predict(W_test)


In [100]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
Accuracy= 100 * accuracy_score(Y_test, Y_pred)
print(Accuracy)


[[12  0]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        84

    accuracy                           1.00        96
   macro avg       1.00      1.00      1.00        96
weighted avg       1.00      1.00      1.00        96

100.0


GAUSSIAN NAIVE BAYE'S

In [101]:
from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()


# fit the model
gnb.fit(W_train, Y_train)

Y_pred = gnb.predict(W_test)
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
accuracy = 100 * (accuracy_score(Y_test, Y_pred))
print(accuracy)

[[ 6  6]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.50      0.67        12
           1       0.93      1.00      0.97        84

    accuracy                           0.94        96
   macro avg       0.97      0.75      0.82        96
weighted avg       0.94      0.94      0.93        96

93.75


Ensemble Learning

In [102]:
from sklearn.ensemble import VotingClassifier

#model_1 = LogisticRegression(random_state=0, solver='liblinear', max_iter=300, multi_class='ovr')
model_2 = XGBClassifier(n_estimators=20)
model_3 = RandomForestClassifier(n_estimators=5, max_depth=5, random_state=1)
model_4 = KNeighborsClassifier(n_neighbors=3)
#model_5 = SVC(kernel="rbf", C=10, gamma=1)
final_model = VotingClassifier(estimators=[#('lr', model_1), 
                                             ('xgb', model_2), 
                                             ('rf', model_3), 
                                             ('knn',model_4)])
                                           #  ('svm', model_5)], voting='hard')
final_model.fit(W_train, Y_train)


Y_pred = final_model.predict(W_test)

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

accuracy = 100 * accuracy_score(Y_test, Y_pred)
  
print("Accuracy = %.2f" % (accuracy))



[[11  1]
 [ 0 84]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        12
           1       0.99      1.00      0.99        84

    accuracy                           0.99        96
   macro avg       0.99      0.96      0.98        96
weighted avg       0.99      0.99      0.99        96

Accuracy = 98.96
